title: Vincent Marichi # your name (or website title) here
logo: "#AvatarMaker.png
" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  This portfolio is created for my web design class.
  <br><br>
  I hope you enjoy my portfolio please contact me if you would hire me as a web or graphic designer
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
